GET http://localhost:8087/employees/avg
Accept: application/json

###
GET http://localhost:8087/employees
Accept: application/json

###

PUT http://localhost:8087/employee/age/1/12
Content-Type: application/json


###
